### ISSUE TITLE
Guest Blog Post

### ISSUE THREAD

**Issue by gep13** [larzw/Cake.Paket#1]
Just wanted to say a huge congratulations, and a thank you, for contributing this addin and module!  I am sure that a lot of people will find it very useful!

I was wondering, would you be interested in doing a guest blog post on the cakebuild.net site introducing both the addin and the module?  I think this would be really helpful, and would introduce it to a number of people.

Let me know what you think.

**Comment by larzw** [comment]
Thank you @gep13! It's a fun side project 😄. I would definitely be interested in a guest blog post. I'll get on that once I get the module and addin in a more stable state.

**Comment by gep13** [comment]
>@larzw said...
I'll get on that once I get the module and addin in a more stable state.

That is great news! Thanks!
